head -10 beach.txt > beach_valid.txt && sed -i '1,+9d' beach.txt
head -10 christmas.txt > christmas_valid.txt && sed -i '1,+9d' christmas.txt
head -10 easter.txt > easter_valid.txt && sed -i '1,+9d' easter.txt
head -10 fashion.txt > fashion_valid.txt && sed -i '1,+9d' fashion.txt
head -10 friends.txt > friends_valid.txt && sed -i '1,+9d' friends.txt
head -10 landscape.txt > landscape_valid.txt && sed -i '1,+9d' landscape.txt
head -10 love.txt > love_valid.txt && sed -i '1,+9d' love.txt
head -10 mountains.txt > mountains_valid.txt && sed -i '1,+9d' mountains.txt
head -10 nature.txt > nature_valid.txt && sed -i '1,+9d' nature.txt
head -10 snow.txt > snow_valid.txt && sed -i '1,+9d' snow.txt
head -10 summer.txt > summer_valid.txt && sed -i '1,+9d' summer.txt
head -10 sunset.txt > sunset_valid.txt && sed -i '1,+9d' sunset.txt